services:
  - type: web
    name: bpmflow
    env: python
    buildCommand: 
      - pip install -r requirements.txt
      - python manage.py collectstatic --noinput
      - python manage.py migrate
    startCommand: gunicorn BPMFlow.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DB_NAME
        value: bpmflow_db
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: root
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: '3306'
      - key: SECRET_KEY
        value: django-insecure-7o)^7s)_b5p5c)*122h_it3+e!c*7ccqdj)b@w@$dq)j=z+86j
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'bpmflow-vqdl.onrender.com bpmflow.onrender.com localhost 127.0.0.1 [::1]'
